position:
  x: 0
  y: 0
  z: -3.25
 
direction:
  x: 0.05
  y: -0.025
  z: -1
 
type: SPOT_LIGHT
 
# the cone is approx. 20 degrees wide, in radians
angle: 0.349
 
# this light has fairly sharp edges.
spot_exponent: 8
 
attenuation:
  constant: 1.0
  linear: 0
  quadratic: 0
 
color:
  ambient:
    red: 0
    green: 0
    blue: 0.4
    alpha: 1
 
  diffuse:
    red: 0
    green: 0
    blue: 1.0
    alpha: 1.0
 
  specular:
    red: 0
    green: 1
    blue: 0
    alpha: 1.0